#!/usr/bin/env bash
#
# The shell script is for calling a python script. To create a command to
# launch XYZ.py, create a symbolic link from this file to XYZ.
#
#     ln -s launcher XYZ
#
name=$(basename "$0").py
script_dir="$(dirname "$(readlink -f "$0")")"
uv run --project $script_dir $script_dir/$name $@
